apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: theme-organization-category-annotations
spec:
  targetRef:
    group: content.halo.run
    kind: Category
  formSchema:
    - $formkit: code
      name: categoryIntro
      label: 分类介绍
